### ISSUE TITLE
Consider add support to pyBullet.

### ISSUE THREAD

**Issue by qiayuanliao** [syuntoku14/fusion2urdf#11]

**Comment by nyxaria** [comment]
How does it not? PyBullet requires only an URDF to function

**Comment by QiayuanLiao** [comment]
> How does it not? PyBullet requires only an URDF to function
 
If I don't have ROS environment, I can't run "stl2binary.bash".

**Comment by syuntoku14** [comment]
stl2binary.bash doesn't require ROS environment. It only requires ruby and python.
