### ISSUE TITLE
Mass Properties

### ISSUE THREAD

**Issue by Cullen-Dubbs** [syuntoku14/fusion2urdf#13]
I dont know if this is a feature that should be implemented or not.  Everything working great btw!

When I create my links they don't seem to carry their mass properties with them? (interia CoM etc)

Any thoughts?

```
<link name="base_link"/>
	<joint name="set_worldaxis" type="fixed">
		<origin rpy="1.570796326795 0 0" xyz="0.0 0.0 0.0"/>
		<parent link="base_link"/>
		<child link="base"/>
		<axis xyz="0 0 0"/>
		<limit effort="0" lower="-1" upper="1" velocity="0"/>
	</joint>
	<link name="base">
		<inertial>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<mass value="0"/>
			<inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
		</inertial>
		<visual>
			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
			<geometry>
				<mesh filename="package://robot_description2/meshes/base.stl"/>
			</geometry>
			<material name="">
				<color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1"/>
			</material>
```

**Comment by syuntoku14** [comment]
Thank you for your feedback!

You mean, the properties of the "base" link?  I guess if you specify the materials in fusion360, they will be defined properly.

Do you specify the material of the "base" link in fusion360?

**Comment by Omginmrobotics** [comment]
Even I am facing the same problem in creating urdf file as the MOI is too small the MOI values are approximated to 0. Hence while getting these values to mujoco it shows an error. This is difficult for very small robots as the MOI is written in kgcm^2. Do tell me if there is any fix for the same.
