### ISSUE TITLE
Usability Improvements (auto-link breaking and renaming)

### ISSUE THREAD

**Issue by blubbi321** [syuntoku14/fusion2urdf#14]
Hey there!

Thanks a lot for your script, it is incredibly useful to me!

Just two remarks to speed up the workflow:
1. As all references of the components need to be broken this costs a lot of time when reexporting arms. As far as I can see breaking the links from Python should be simple enough? (https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-7f7547c0-702d-11e7-8712-6c0b84aa5a3f)
2. The requirement for "no spaces in component names" could probably also be automated away? It also eats up a lot of time removing all these v123 from names like "xxxx v123"

I'll pick up this issue myself if I happen to get more time for OS work in the future, for now Im just dumping my ideas here, sorry for that!

**Comment by syuntoku14** [comment]
Thanks for your feedback!

Sorry that there are still a lot of problems. I can't make time now, but I'll try to fix the problem as soon as possible.
Next time I'll work on your idea, refactoring and supporting nested components, etc.

**Comment by blubbi321** [comment]
Uh, supporting nested components would be even better :D

**Comment by nyxaria** [comment]
Thank you so much Syuntoku for taking the time out of your day to do this. You are so awesome :)

**Comment by syuntoku14** [comment]
I fixed the second problem, but the first problem is remaining
Reexporting is necessary to move the relative origins of the links to the world origin.
