### ISSUE TITLE
there seems to be an error between [component] and [other component]

### ISSUE THREAD

**Issue by nikisalli** [syuntoku14/fusion2urdf#24]
![image](https://user-images.githubusercontent.com/31286021/70735490-a8fb2380-1d0e-11ea-85e5-278d8e6e57e7.png)

what does this mean?
this is what my model component tree looks like:
![image](https://user-images.githubusercontent.com/31286021/70735657-f5466380-1d0e-11ea-9cc5-61d4de450019.png)

**Comment by nikisalli** [comment]
nevermind, solved! it was that there were no joints between the revolute joints and the component named base_link. after creating some rigid joints between the base_link component and the other components everything works fine

**Comment by nyxaria** [comment]
Maybe this should get a better error message?

**Comment by nikisalli** [comment]
yeah maybe this could be added to the error message like "check [same error as before] and if the base_link component is connected to the rest of the parts"
