### ISSUE TITLE
Model rotated in Rviz and Gazebo

### ISSUE THREAD

**Issue by PranshuTople** [syuntoku14/fusion2urdf#30]
First of all thank you very much on such helpful repository!

Everything works well, but whenever i spawn my robot in Rviz or Gazebo, the model is rolled 90 degrees. In gazebo, that can be corrected by selecting the object (robot), but i am unable to do the same in Rviz. could you please help me with that?

**Comment by blubbi321** [comment]
From the readme: 
> The following test model doesn't stand upright because z axis is not upright in default fusion 360. Make sure z axis is upright in your fusion 360 model if you want.

**Comment by PranshuTople** [comment]
The solution can be found here:
https://youtu.be/1zB7rc2DBjk?t=117
