### ISSUE TITLE
Simple example?

### ISSUE THREAD

**Issue by OBMGMT** [syuntoku14/fusion2urdf#33]
Hello Toshinori, I'm hoping you can help. I've been able to get this all up and running, and I've successfully exported the complex Industrial Robot Arm into rviz. However, I cannot seem to create a jointed model in Fusion 360 that will display properly in rviz or gazebo.

The model is very simple, but no matter what I do I can't get additional components to appear in rviz. Can you please offer some advice? Maybe some steps to create a very simple model as a starting point? I'm starting small before building out my robot arm in Fusion 360, so I wanted to get something simple working first. I hope you can help. Thank you!
![01](https://user-images.githubusercontent.com/5171294/88732414-bb7d7c80-d17a-11ea-8c04-30c118a0fefb.PNG)
![02](https://user-images.githubusercontent.com/5171294/88732433-bcaea980-d17a-11ea-8f27-cb6f36e7f47e.PNG)

**Comment by thakur12707** [comment]
Hello, have you found any solution I am new to ros and trying out thing and got the same error.

**Comment by thakur12707** [comment]
Hey I got the answer you should be using Normal joints instead of As-built joint
