### ISSUE TITLE
Links/joints with offsets on latest Fusion360's version

### ISSUE THREAD

**Issue by SimonDiazAbad** [syuntoku14/fusion2urdf#45]
Hello, I've been using this script for months and has worked great until some days ago after a Fusion360 update. I took the URDF files of a robot that worked fine, generated them again and now its links have big offsets and joints have origins really close to 0. When loading this into RViz I can see the robot in the starting position as it should but when joints are moved, they all just spin around the map center. Is there any way to fix it? Any help is appreciated.

**Comment by SpaceMaster85** [comment]
Hello, I can confirm the problem. Joints are rotating around the map center. Hoping also for help. Thank you very much!
