### ISSUE TITLE
Issues with ROS (neodic Ubuntu 20.4) when I try to launch the display.launch

### ISSUE THREAD

**Issue by Quentbern** [syuntoku14/fusion2urdf#49]
Hi
I try with the robot in the description. I have the URDF files provide by Fusion 360 and the script.
However, when I try in ROS. I have this error : 
![image](https://user-images.githubusercontent.com/79104974/115197192-01a3b300-a0f1-11eb-9106-00a547eca125.png)

I try the other launch file, same error.
Thank in adavance for the help.
Best

**Comment by carpit680** [comment]
Did you modify the xacro or launch files? Could you try exporting it again and provide the description package if possible?

**Comment by Quentbern** [comment]
It's working now. 
First, I had this : "é" in my URDF files.
Secondly, I modify the launch files and now it's working.
Thank you
