### ISSUE TITLE
Intertial and collisions problem 

### ISSUE THREAD

**Issue by raess1** [syuntoku14/fusion2urdf#5]
Exporter works. Having hard time getting the Intertial and collisions to compute/display properly in gazebo.
Any suggestions on this?

**Comment by syuntoku14** [comment]
Thank you for notifying me.
I displayed the inertial and collisions of my test model.
- test model
![image](https://user-images.githubusercontent.com/29631982/45605409-a6b5f680-b9f1-11e8-9d8a-d4bb052e4b0a.png)
- inertial
![image](https://user-images.githubusercontent.com/29631982/45606162-a1f44100-b9f7-11e8-8d9f-3204415dcc27.png)

- collisions
![image](https://user-images.githubusercontent.com/29631982/45606105-3b6f2300-b9f7-11e8-8951-2e4ea8421696.png)


I'm not used to Gazebo, so I am not sure about the inertial well. Is not the inertial in the above image computed properly?
As for the collisions, I think it works well. You can display your model's colliision by right clicking Models-> "your robot" and select View->Collisions. You can see the inertial in the same way.

**Comment by raess1** [comment]
Hm hard to tell if the inertial and mass works correctly from the  above pictures. If you look at it the Center of Mass in Gazebo does they also compute correct? When I display the Center of Mass they seem not to reflect the realitythe cad Program. 

The main issue with my robot is that the joints are moving around like crazy, Hence the question on the intertial and collisions. 

Let me attach some pictures (soon)

**Comment by syuntoku14** [comment]
I found that the Center of Mass doesn't reflect the information correctly.
![image](https://user-images.githubusercontent.com/29631982/45607554-07e5c600-ba02-11e8-96cf-d59d1bd40d54.png)
I think there should be some problems with my codes to compute the location of the mass. Inertia information can cause that issue.
I'll fix this at a later date.

**Comment by raess1** [comment]
Yeah, that looks more or less what I also got.. I wonder how it looks if we dont use the script to binary STL? could it be a scaling issue for the mass and inertia?

Are you able to controll that arm correctly in gazebo? I guess without correct COG and Inertia the sim will not work correctly.

**Comment by syuntoku14** [comment]
I fixed the bug. Use the latest version and check whether everything works or not.
Let me know the result if you can.

**Comment by raess1** [comment]
Great! Let me give you feedback tomorrow

**Comment by raess1** [comment]
works nicely! :)
