### ISSUE TITLE
Problem with the Joint origin

### ISSUE THREAD

**Issue by Quentbern** [syuntoku14/fusion2urdf#50]
Hi 
I have the right model on Gazebo but the Joint are wrong. They are in the wrong place.
Is this problem came from Fusion 360 with the links ?
Or what is the solution to fix this ?

Thanks in advance

**Comment by Quentbern** [comment]
I find the soltion myself. 
be careful when you create your robot in Fusion 360.
The origin of the pieces has to be the center of the joint. 
I do this and I have no problem now.

**Comment by hiphyu** [comment]
hi, if you don't mind, could you see my post issue?
https://github.com/syuntoku14/fusion2urdf/issues/98

since i see this issue is similar to mine, could you please help me check what's wrong? I've already fixed it as you said in your previous solution, thanks
