### ISSUE TITLE
Joint Types other than revolute

### ISSUE THREAD

**Issue by nyxaria** [syuntoku14/fusion2urdf#6]
Hi,

Do you plan on adding other joint types than revolute? I am in need to using the linear/sliding joint type.

Thank you :)

**Comment by syuntoku14** [comment]
Thank you for your request.
Yes, I'm planning to add that features.
Unfortunately, my school starts and I cannot make enough time. But I'll definitely do it.

**Comment by syuntoku14** [comment]
I added joint type "Rigid" and "Slider" to the branch "add_joint_type".
Can you try this and tell me the feedback?

**Comment by nyxaria** [comment]
Hello, thank you for the quick feedback- I will test it and get back to you :) I am currently also at work, but I will try to do it as soon as possible

**Comment by nyxaria** [comment]
I prepared a simple model with the slider joint, but I am unable to export the model because of the following error: https://i.imgur.com/QPXZauz.png
I took the courtesy to edit the source code to also print the joints_dict in the error popup for debugging purposes. 
Do you know why this is happening? I presume it is because of the name 'base_link:1' but am unsure as to how to resolve this, nor that there are instances of 'base_link_1' and 'base_link__1', note the double underscore in the second.
The name of the two components are 'alum_tube_OD35mmL250mmT3mm' and 'base_link', yet both have ':1' after them in the tree view of the components, as can be seen in the screenshot. 
Thanks for your help!

**Comment by syuntoku14** [comment]
It seems that your component name doesn't match "base_link". Can you redefine "base_link" and try again? 
If you still can't get things to work, please share your model in some way.


I made a simple model for testing "Rigid" and "Slider" joints and run the script. 

![slider](https://user-images.githubusercontent.com/29631982/46047352-aa283c80-c0d9-11e8-988d-b0c1e39d978a.png)

![screenshot from 2018-09-25 14-44-15](https://user-images.githubusercontent.com/29631982/46047343-9f6da780-c0d9-11e8-952d-1265fbb26e09.png)

In my case, the add-in works fine.

**Comment by syuntoku14** [comment]
Sorry, I can't find any cause of the bugs from only this image.
Can you redefine the joint and try again?
If you still can't get things to work, can you share your model in some way?

In my case, joints "Rigid" and "Slider" are properly exported to urdf.
![slider](https://user-images.githubusercontent.com/29631982/46047776-3dae3d00-c0db-11e8-9de4-db3242388fec.png)
![screenshot from 2018-09-25 14-44-15](https://user-images.githubusercontent.com/29631982/46047785-4272f100-c0db-11e8-9bcd-7a5074bc1612.png)

**Comment by nyxaria** [comment]
I have just remade my simple model, as you suggested-- and it works! 

I have no idea why the previous version didn't, but regardless, thank you for the quick help! =) 

You are awesome!

**Comment by syuntoku14** [comment]
I found that the error you mentioned occurs when the parent link is set as joint "Component1".
![image](https://user-images.githubusercontent.com/29631982/46251665-41f59580-c40e-11e8-9c5a-0a1cb2152520.png)
Therefore, it works fine only if you set base_link as "Component2".
