### ISSUE TITLE
Script not working after updating the Fusion360

### ISSUE THREAD

**Issue by x-dev-s** [syuntoku14/fusion2urdf#81]
After updating the software to the latest version, the script is not working. It does nothing when I run it. No browse window or anything is opening. I removed the script from the fusion360 and then added it again, but it is still not working.

**Any help, please!!!**

**Comment by ShikurM56** [comment]
Go to the script's folder, go to utils, and modify utils.py

go to the function copy_package and use the following code:

```
def copy_package(save_dir, package_dir):
    try: 
        os.mkdir(save_dir + '/launch')
    except: 
        pass
    try: 
        os.mkdir(save_dir + '/urdf')
    except: 
        pass
    # shutil.copytree replaces copy_tree
    shutil.copytree(package_dir, save_dir, dirs_exist_ok=True)
```

Don't forget to add the library
`
import shutil  # Add this import
`

Regards,

**Comment by x-dev-s** [comment]
**Thank you for the help @ShikurM56** 

Works perfectly ❤

**Comment by Prithvijai** [comment]
I did the mentioned changes still it doesn't work

**Comment by ShikurM56** [comment]
Remove copy tree library

**Comment by Prithvijai** [comment]
Hii , I removed the library and It worked . Thank you so much.
