### ISSUE TITLE
Error while running urdf_exporter

### ISSUE THREAD

**Issue by chaolmu** [syuntoku14/fusion2urdf#9]
could you help:
![default](https://user-images.githubusercontent.com/9334182/47884163-0183a000-de30-11e8-87f4-6cffefd48162.PNG)

**Comment by nyxaria** [comment]
Did you fully define the joint limits?

**Comment by syuntoku14** [comment]
Hi, 
sorry for the late response.

Can you try to redefine the joint attached to base_link?
This error may happen when the relationship between the parent and the child of a joint is the other way around.

The parent links should be set as Component2 when you define the joint not as Component1.

**Comment by chaolmu** [comment]
I have combined different components together as base_link and remove all propeller but one left. So the model have only 2 links and 1 revolute joint. However I got the same error:
![image](https://user-images.githubusercontent.com/9334182/48233511-c6e0b100-e3b5-11e8-8747-a53416b08d28.png)

**Comment by chaolmu** [comment]
I have delete the model until one propeller and one motor left, the same error occurs. Then I open a new file and import a propeller and a motor, define the joint as before. The urdf exporter has successfully excuted. Interesting...

**Comment by syuntoku14** [comment]
Thank you for your feedback.

The error says the "component2" is not defined, but your model looks define the joint properly. I don't have any idea why it occurs...

It can be sometimes solved by just redefining the joint.
